import fs from "node:fs";
import path from "node:path";
import calver from "calver";

const root = process.cwd();
const outFile = path.join(root, "src", "oracle_test.mbt");

const valid = [
  "0.0.0",
  "0.1.0",
  "1.0.0",
  "1.0.0-alpha",
  "1.0.0-alpha.1",
  "1.0.0-alpha.beta",
  "1.0.0-beta",
  "1.0.0-beta.2",
  "1.0.0-beta.11",
  "1.0.0-rc.1",
  "1.2.3",
  "1.2.3-alpha.1+build.5",
  "1.2.3+build.1",
  "1.2.3+build.2",
  "1.2.3-alpha+build.1",
  "2.0.0",
  "2.1.0",
  "2.1.1",
];

const invalid = [
  "",
  "1",
  "1.0",
  "01.0.0",
  "1.01.0",
  "1.0.01",
  "1.0.0-01",
  "1.0.0-",
  "1.0.0+",
  "1.0.0-alpha..1",
  "1.0.0-alpha.",
  "1.0.0+build..1",
  "1.0.0+build.",
  "1.0.0+build..",
  "1.0.0-α",
  "1.0.0+α",
  "1.0.0+build!",
];

const strictValid = valid.filter((v) => calver.valid(v, { loose: false }) === v);
const strictInvalid = invalid.filter((v) => calver.valid(v, { loose: false }) === null);

const pairs = [];
for (const a of strictValid) {
  for (const b of strictValid) {
    const cmp = calver.compare(a, b, { loose: false });
    pairs.push([a, b, cmp]);
  }
}

function escapeString(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function emit() {
  const lines = [];
  lines.push("// Generated by scripts/gen_oracle.mjs. Do not edit by hand.");
  lines.push("///|");
  lines.push('test "oracle valid compare" {');
  lines.push("  let cases : Array[(String, String, Int)] = [");
  for (const [a, b, cmp] of pairs) {
    lines.push(`    ("${escapeString(a)}", "${escapeString(b)}", ${cmp}),`);
  }
  lines.push("  ]");
  lines.push("  for item in cases {");
  lines.push("    let (a, b, expected) = item");
  lines.push("    let va = parse(a)");
  lines.push("    let vb = parse(b)");
  lines.push("    assert_eq(va.compare(vb), expected)");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("///|");
  lines.push('test "oracle invalid parse" {');
  lines.push("  let cases : Array[String] = [");
  for (const v of strictInvalid) {
    lines.push(`    "${escapeString(v)}",`);
  }
  lines.push("  ]");
  lines.push("  for s in cases {");
  lines.push("    let result : Result[calver, calverError] = try? parse(s)");
  lines.push("    assert_true(result is Err(_))");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, emit(), "utf8");
console.log(`wrote ${path.relative(root, outFile)}`);
